### ISSUE TITLE
Network loss event handling

### ISSUE THREAD

**Issue by rsemenoff** [miguelgrinberg/microdot#146]
I'm using microdot for my remote-controlled vehicle application. I need to be able to gracefully stop the vehicle if the wifi range is exceeded and the connection drops. 

I see there is provision for catching exceptions, but I don't see that microdot generates special exception for network being dropped.
I've considered creating a process to periodically poll the network interface status; But I thought I'd raise this here first, in case there is a better or easier way to do this within microdot, or whether it should be part of the microdot framework at all...

**Comment by miguelgrinberg** [comment]
Microdot does not attempt to manage or configure networking. This is by design, because different platforms have different requirements. I suppose you can catch the expect that your board raises when networking is lost by wrapping the `app.run()` call in a try/except block, and when that happens attempt to reconnect and restart the server.
